name: Build test
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - name: Git config
      run: git config --global core.symlinks true
      if: startsWith(matrix.platform, 'windows-')
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install packages(Ubuntu)
      if: startsWith(matrix.platform, 'ubuntu-')
      run: sudo apt install liblz4-dev sip-dev libeigen3-dev sip-dev libboost-all-dev
    - name: Install packages(MacOS)
      if: startsWith(matrix.platform, 'macos-')
      run: brew install eigen boost
    - name: Install packages(Windows)
      if: startsWith(matrix.platform, 'windows-')
      run: |
        curl -LO -s "https://github.com/lz4/lz4/archive/v1.9.2.zip"
        unzip -q v1.9.2.zip -d roslz4
        "/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe" "roslz4\lz4-1.9.2\visual\VS2017\lz4.sln" //t:liblz4 //p:Configuration=Release //p:Platform="x64" //p:ForceImportBeforeCppTargets="D:\a\simple\simple\roslz4\build.props" //p:WindowsTargetPlatformVersion="10.0.18362.0"
        curl -LO -s "https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.zip"
        unzip -q eigen-3.3.7.zip -d PyKDL
        echo ::set-env name=EIGEN_ROOT::eigen-3.3.7
      shell: bash
    - name: Install rospy-build
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
        pip install "git+https://github.com/ros-infrastructure/catkin_pkg.git#egg=0.4.13"
        pip install "git+https://github.com/ros/genmsg.git#egg=0.5.12"
        pip install "git+https://github.com/ros/genpy.git@4a094eaaa79c379593badcdea58060e26f9fe933"
        pip install rospy-builder/
    - name: Download existing packages
      run: |
        git clone -b gh-pages https://github.com/rospypi/simple.git index
      if: startsWith(matrix.platform, 'ubuntu-') && startsWith(matrix.python-version, '3.8')
    - name: Build platform specific binary packages
      run: |
        rospy-build build --local
    - name: Build universal packages
      run: |
        rospy-build build
      if: startsWith(matrix.platform, 'ubuntu-') && startsWith(matrix.python-version, '3.8')
